import time
print("i0 import", flush=True)
t0 = time.time()
import seed_demo_data as S
print("i1 imported", round(time.time() - t0, 2), flush=True)
t0 = time.time()
p = S.mk_phone()
print("i2 phone", p, round(time.time() - t0, 2), flush=True)
t0 = time.time()
e = S.mk_email("Probe", "Emp")
print("i3 email", e, round(time.time() - t0, 2), flush=True)
t0 = time.time()
n = S.mk_nik("Banyumas", "1990-05-17")
print("i4 nik", n, round(time.time() - t0, 2), flush=True)
print("done", flush=True)
